baseURL: "https://AnuragSinghChaudhary.github.io/"
languageCode: en-us
title: Anurag 
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 45
    # - identifier: projects
    #   name: Research Papers
    #   url: /projects
    #   weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Anurag singh Chaudhary"
    subtitle: Hi 👋 I'm Anurag, Let's connect!

 
    imageUrl: "home/Anurag_profile_pic_1.png"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:Anuragchaudahry004@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/anurag-singh-chaudhary"
    - name: "github"
      url: "https://github.com/AnuragSinghChaudhary"
    - name: "youtube"
      url: "https://www.youtube.com/@anrag"
    - name: "twitter"
      url: "https://x.com/Anurag_chdry"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
